Repository pelcro-inc/react-pelcro-js, pull requests merged in 2021-11, with the labels that each got.

#100 feat(checkout): display tax inclusive price at checkout
  src/Components/PaymentMethod/CouponCode.js
  src/Components/PaymentMethod/CouponCodeField.js
  src/Components/PaymentMethod/DiscountedPrice.js
  src/Components/PaymentMethod/PaymentMethodContainer.js
  src/Components/PaymentMethod/PaymentMethodView.js
  src/Components/PaymentMethod/TaxAmount.js
  src/components.js
  src/translations/en/checkoutForm.json
  src/translations/fr/checkoutForm.json
  src/utils/action-types.js
Labels: enhancement

#101 feat: add update newsletters modal
  public/index.html
  src/Components/NewsletterUpdate/NewsletterUpdateButton.js
  src/Components/NewsletterUpdate/NewsletterUpdateContainer.js
  src/Components/NewsletterUpdate/NewsletterUpdateList.js
  src/Components/NewsletterUpdate/NewsletterUpdateModal.js
  src/Components/NewsletterUpdate/NewsletterUpdateView.js
  src/Components/common/PelcroNativeButtons/index.js
  src/Components/dashboard/Dashboard.js
  src/Main.js
  src/assets/newsletter.svg
  src/components.js
  src/hooks/usePelcro/pelcroActions.js
  src/hooks/usePelcro/usePelcro.test.js
  src/translations/en/dashboard.json
  src/translations/en/newsletter.json
  src/translations/fr/dashboard.json
  src/translations/fr/newsletter.json
  src/utils/action-types.js
  src/utils/utils.js
Labels: enhancement

#103 fix: enforce having no border for multiple buttons
  src/Components/Meter/MeterModal.js
  src/Components/dashboard/DashboardOpenButton.js
  src/SubComponents/Alert.css
  src/SubComponents/Button.css
  src/SubComponents/Modal.css
Labels: enhancement

#104 fix: enforce buttons colors
  src/Components/Meter/MeterModal.js
  src/SubComponents/Alert.css
  src/SubComponents/Button.css
  src/SubComponents/Modal.css
Labels: enhancement

#102 fix(coupon): display discounted amount before taxes
  src/Components/PaymentMethod/DiscountedPrice.js
  src/Components/PaymentMethod/PaymentMethodContainer.js
Labels: bug, enhancement

#105 feat(dashboard): close menu when user clicks outside
  src/Components/dashboard/Dashboard.js
Labels: enhancement

#106 feat(url triggers): allow opening newsletters update modal for non authed users
  src/Components/NewsletterUpdate/NewsletterUpdateContainer.js
  src/hooks/usePelcro/pelcroActions.js
  src/translations/en/newsletter.json
  src/translations/fr/newsletter.json
Labels: enhancement

#107 fix(url triggers): newsletters update trigger breaking paywalls
  src/Components/NewsletterUpdate/NewsletterUpdateContainer.js
  src/hooks/usePelcro/pelcroActions.js
  src/utils/utils.js
Labels: enhancement

#109 feat(newsletters update): update success wording
  src/translations/en/newsletter.json
  src/translations/fr/newsletter.json
Labels: enhancement

#110 feat(dashboard): add css classes for sub action buttons
  src/Components/dashboard/Dashboard.js
  src/components.js
Labels: enhancement

#112 feat: lazy load Stripe SDK
  package.json
  rollup.config.js
  src/Components/PelcroModalController/PelcroModalController.service.js
  yarn.lock
Labels: enhancement

#114 feat(i18n): use and observe page language in all UI
  public/index.html
  src/Components/OrderConfirm/OrderConfirmModal.js
  src/Components/PaymentMethod/DiscountedPrice.js
  src/Components/PaymentMethod/PaymentMethodContainer.js
  src/Components/PaymentMethod/SubmitPaymentMethod.js
  src/Components/PaymentMethod/TaxAmount.js
  src/Components/SubscriptionCreate/SubscriptionCreateView.js
  src/Components/common/FacebookLoginButton/FacebookLoginButton.js
  src/Components/dashboard/Dashboard.js
  src/Components/dashboard/DashboardMenus/OrdersMenu.js
  src/i18n.js
  src/services/PayPal/PaypalCheckout.service.js
  src/utils/utils.js
Labels: enhancement

#115 fix(gift creation): error dispatched if gift date is set to today
  src/Components/GiftCreate/GiftCreateContainer.js
  src/utils/utils.js
Labels: bug

#116 feat: add expiremental security token support
  src/Components/PelcroModalController/PelcroModalController.js
  src/Components/PelcroModalController/PelcroModalController.service.js
  src/Components/Register/RegisterButton.js
  src/Components/Register/RegisterContainer.js
Labels: enhancement
